server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:1y1y00/springcloud-configg.git #GitHub上面的git仓库名字
        ####搜索目录
          search-paths:
            - springcloud-configg
          username: 501625574@qq.com
          password: 931108yyyhh
      ####读取分支
      label: master
#rabbitmq相关配置
#rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


